version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  spotbugs:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Spot Bug
          command: mvn spotbugs:check

  checkstyle:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Checkstyle
          command: mvn checkstyle:check

workflows:
  sample:
    jobs:
      - build-and-test
      - checkstyle
      - spotbugs